### ISSUE TITLE
Change splat descriptor syntax on path

### ISSUE THREAD

**Issue by cappslock** [SQUARE-WAVES/PDL#1]
Currently this does :paramname for a required path parameter and :paramname? for an optional path parameter, but +splat for a required splat and *splat for an optional splat.

Let's standardize the splats to be *splat and *splat?

**Comment by SQUARE-WAVES** [comment]
this was done a while back but I forgot to close the issue. splats are now like:

```
/dogs/cats/*otherstuff?
```
