### ISSUE TITLE
Splats should be required in params

### ISSUE THREAD

**Issue by cappslock** [SQUARE-WAVES/PDL#2]
If you use a splat on a path e.g. /stuff/*splabs, this currently doesn't need to be an explicitly specified param. It probably should be, with type: "splat".

**Comment by SQUARE-WAVES** [comment]
yeah, I'm not gonna do this, for the sake of keeping things in the simplest case super simple. this way if you don't want to bother with matcher schemas you can just write paths like /x/:y/*z and be done
